{% set version = "0.10.1" %}
{%set hash_type = "sha256" %}
{%set hash_val = "4b17d5bc1a59433ecb3e7668541abf003274910688bfbe221a4aa10e7271ed4a" %}

package:
  name: ggplot
  version: {{ version }}

source:
  fn: ggplot-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/g/ggplot/ggplot-{{ version }}.tar.gz
  {{ hash_type }}: {{ hash_val }}
  patch:
    - py3.patch  # [py3k]
    # See 0e05e in the base repo; should be removed next version

build:
  number: 1
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
    - brewer2mpl
    - cycler
    - matplotlib
    - numpy
    - pandas
    - patsy >=0.4
    - scipy
    - six
    - statsmodels

  run:
    - python
    - brewer2mpl
    - cycler
    - matplotlib
    - numpy
    - pandas
    - patsy >=0.4
    - scipy
    - six
    - statsmodels
    - icu  # [win and py34]
    # The above is a workaround for a mystery issue with PyQT

test:
  imports:
    - ggplot

about:
  home: https://github.com/yhat/ggplot
  license: BSD 2-Clause
  summary: 'ggplot for python'

extra:
  recipe-maintainers:
    - pmlandwehr
    - ocefpaf
