{% set name = "ggplot" %}
{% set version = "0.11.5" %}
{% set bundle = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash = "48bbc9ea5987f815ad25856d76573506dbfe153ff696f026ce324582af56469f" %}
{% set build = 2 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.io/packages/source/g/ggplot/ggplot-{{ version }}.{{ bundle }}
  {{ hash_type }}: {{ hash }}

build:
  number: {{ build }}
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - brewer2mpl
    - cycler
    - matplotlib
    - numpy
    - pandas
    - patsy >=0.4
    - pyqt 4.11.*
    - qt 4.8.*
    - scipy
    - six
    - statsmodels

test:
  imports:
    - ggplot

about:
  home: https://github.com/yhat/ggplot
  license_file: LICENSE
  license: BSD 2-Clause
  license_family: BSD
  summary: 'ggplot for python'
  dev_url: https://github.com/yhat/ggplot
  doc_url: https://github.com/yhat/ggplot/tree/master/docs

extra:
  recipe-maintainers:
    - pmlandwehr
    - ocefpaf
