{% set version = "0.11.5" %}

package:
  name: ggplot
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/g/ggplot/ggplot-{{ version }}.tar.gz
  sha256: 48bbc9ea5987f815ad25856d76573506dbfe153ff696f026ce324582af56469f

build:
  number: 4
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip
  run:
    - python
    - brewer2mpl
    - cycler
    - matplotlib
    - numpy
    - pandas <=0.22.0
    - patsy >=0.4
    - pyqt 4.11.*
    - qt 4.8.*
    - scipy
    - six
    - statsmodels

test:
  imports:
    - ggplot

about:
  home: https://github.com/yhat/ggplot
  license_file: {{ RECIPE_DIR }}/LICENSE
  license: BSD 2-Clause
  license_family: BSD
  summary: 'ggplot for python'
  dev_url: https://github.com/yhat/ggplot
  doc_url: https://github.com/yhat/ggplot/tree/master/docs

extra:
  recipe-maintainers:
    - pmlandwehr
    - ocefpaf
