travis:
  secure:
    BINSTAR_TOKEN: V4mXmXJDM6uHjZjeoaK3Uy2FXHycWRZI3P4biCATFwBxK261TS9/8yww4V0We/fnLuuNcvmUILoFx9O878P1vds78UIfhHcqAV+cACRHcoW8lyYWdc0lefYxeho0iNoKh3iDIqRpfBFKYZn3MRtW5S3lFgXSL1ScqwhQDW3gW6N+KVBzESb1D+jjXM9bKT4+LwCCm0t+WLMVQAUX7hrQVIbrlZaIWydjEgafA2VzMtln9qyukBX+aKBj01pDuqz4UpN35TXZ8fPWIdEzQX2L6a0uq3Oh50S3VHj/3ijyPrM6pQU/5b9OXpr9aWacqSoG+iEGB5bC59n3ICq6dm0P3+ZwKUtwBgCeSeIIE6GdYvt8+8ijaakyR8z9gXc51a4h8VRaXc1+Q8AsEtMQUkA8JpsxtAhvPeFxGZgYuD+fvH+QQK1qKVy//AW0WCxYlIy1xoIDx9R3+nWZnKksqKOQPZ6DGXqF9EX1uYTn57om2kkuod6oMqbZscBqJ/v1bDMt4khS2s38vlPHdd/gqM+6okAtU/UZOf+vV1zS5+K3NYA/AVOEqm32i8E1vBNMLh2q7mV/vdJtnSG2NjEvQtiaiGARPKfLpPLgKq4de2D/Wpxjyhqv+qb21c7pPHEnPpqWhv095RUpCphfTys2aFatbraJKKkeKpIE7KGcftx+5E4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
