travis:
  secure:
    BINSTAR_TOKEN: Pb6A+fyc1NtByOlkFWvmcUYRyZKHc2mBnSDav8Uey6JNlxVVWsZRYz5ARqrMiEIQbnWmY3I28S5uj0cKsVZS0WVkvdv4R72lBNlOo0ZJ3C91/PUW8yPH1CCAd7kLUntbyt4MOfXdHooMN1LPCrezG7SPrQIdcKn4LF+rKjs18RFfiYlH44w4JT0xbWQYrr1J/2KBE6FvPq2F1GuNA6s5tJtNe8K7GY6KEcsbrN9IcjMi/oiwm0Z/xKZ25r7unyOmRgsuWXBBUCbxUYCaj8EbBkFnUC64b0LzhiyiAIbNlmQlTrYSzdeFy7CF9CBjIzohMaKUo31qckchTm8Bqt6K0c2x6CV2TrRN3Ia85hcifWR4D1DzRL1cRkeKC2wDGYr7KSS0wGzo4Pa29VT3w9p3URTYASIlhd1LoabnD1VwwitJi6vQlXw0Xv/kpoB3YrtDi0ch/sljwqFZwFDlkxUHSjLJUqfmo3nYcBfrqs57Cq54mF7w6LmjZUMeD9gK9gNBs5GQXqmjBbhn5g2l7wr4gKZ9HHIpkH4S6GR9pJEnkVgHsfjf0dtwCWcDSBWo5IRYj7UG0tAzlG5IarqVHgUHF2/Jcl3BuhssEK37PcemerHoPmAx7xpAntrrwpcXGi2UzdvHJWJrljfYj9Av8nBwiRb/+7Y6Q3x0uifOoC08jJ8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
